### ISSUE TITLE
字体为什么奇奇怪怪的？

### ISSUE THREAD

**Issue by kaituoxu** [LinuxStory/Advanced-Bash-Scripting-Guide-in-Chinese#102]
下载的pdf里面字体不统一啊！汉字的字体奇奇怪怪的
![image](https://cloud.githubusercontent.com/assets/14189886/18409409/e4b67292-7778-11e6-856f-018bcc94e115.png)

**Comment by imcmy** [comment]
Gitbook对中文的字体支持并不好，字体问题会在整本书翻译完成之后再进行解决。
谢谢支持

**Comment by kaituoxu** [comment]
thx!
