### ISSUE TITLE
刚好也在另行翻译

### ISSUE THREAD

**Issue by ShadowRZ** [LinuxStory/Advanced-Bash-Scripting-Guide-in-Chinese#127]
我刚好也在另行翻译这篇文档……🤦‍♀️

我的版本：https://abs-guide-zh.readthedocs.io/zh_CN/latest/

要不我去把剩下那点没人领的偷偷收了（（（（

**Comment by imcmy** [comment]
非常欢迎

**Comment by ShadowRZ** [comment]
我已经把附录 E. F. H. M. 收走了
接下来可能要收走所有没人领的附录（主目录上还有许多收走然后全部没了动静的章节）

最好看一下我的翻译的语言风格
-- 
使用 K-9 Mail 发送自我的Android设备。

**Comment by imcmy** [comment]
收走的话就按照README里面说的提交PR更新就好。😁
项目之前停滞了几年，所以如果还没有翻译的章节，大可以把人给删去换上自己的。
因为本身是多人翻译，所以风格本身就会不一样，只要能够表达出正确意思就可以。

**Comment by ShadowRZ** [comment]
重启之后我想改用新 GitBook 提供的语法（我这个版本用的 Sphinx，源格式是 reStructuredText）

https://docs.gitbook.com/content-editing/markdown#hints-and-callouts

**Comment by imcmy** [comment]
👍这个没问题

**Comment by ShadowRZ** [comment]
准备好了：#130 

Closes #127
