### ISSUE TITLE
7.2 文件测试操作 样例7-4 变量命名问题

### ISSUE THREAD

**Issue by Administroot** [LinuxStory/Advanced-Bash-Scripting-Guide-in-Chinese#155]
### 问题
**样例7-4**在变量`directory`及`directorys`的命名上存在笔误。
```shell
< [ $# -eq 0 ] && directory=$(pwd) || directory=$@
---
> [ $# -eq 0 ] && directorys=$(pwd) || directorys=$@
---
< for directory in $direcotrys; do
---
> for directory in $directorys; do
``` 

### 现象
尝试使用译著的用例无法得到预期效果
测试的环境如下，其中../test目录不存在：
```shell
test1
├── null.txt -> /dev/null
├── test
├── test.txt
└── test2 -> ../test2
``` 

> 预期效果
```shell
"test1/test2"
``` 

> 实际效果
```shell

``` 

---
[原著链接](https://tldp.org/LDP/abs/html/fto.html)
[译著链接](https://linuxstory.gitbook.io/advanced-bash-scripting-guide-in-chinese/zheng-wen/part2/07_tests/07_2_file_test_operators)

**Comment by imcmy** [comment]
Thanks for pointing it out.
