### ISSUE TITLE
Gitbook 第16章译文未正常显示

### ISSUE THREAD

**Issue by Administroot** [LinuxStory/Advanced-Bash-Scripting-Guide-in-Chinese#163]
## 现象
第16章的译文均未正常显示。
> [16.1 基础命令](https://linuxstory.gitbook.io/advanced-bash-scripting-guide-in-chinese/zheng-wen/part4/16.-wai-bu-shai-xuan-qi-ren-wu-ji-ming-ling/16.1-ji-chu-ming-ling) [16.2 复杂命令](https://linuxstory.gitbook.io/advanced-bash-scripting-guide-in-chinese/zheng-wen/part4/16.-wai-bu-shai-xuan-qi-ren-wu-ji-ming-ling/16.2-fu-za-ming-ling) [16.3 时间/日期命令](https://linuxstory.gitbook.io/advanced-bash-scripting-guide-in-chinese/zheng-wen/part4/16.-wai-bu-shai-xuan-qi-ren-wu-ji-ming-ling/16.3-shi-jian-ri-qi-ming-ling) [16.4 文本处理命令](https://linuxstory.gitbook.io/advanced-bash-scripting-guide-in-chinese/zheng-wen/part4/16.-wai-bu-shai-xuan-qi-ren-wu-ji-ming-ling/16.4-wen-ben-chu-li-ming-ling)

## 可能原因
uri未正确匹配。如`16.1 基础命令`uri定位至`16.1-ji-chu-ming-ling`，而远程仓库不存在该文件，应为`16_1_basic_commands`。
其他同理。

### 方案一

1. 检查本地`SUMMARY.md`索引是否有误，有则进行修改。
2. 清理自动生成的文件，如`16.1-ji-chu-ming-ling.md`。
3. 重启服务，执行`gitbook serve`。
### 方案二

1. 备份并清理本地**Gitbook**个性化设置及文件。
2. 同步远程**Github**仓库。
3. 恢复个性化设置及文件。
4. 重启服务，执行`gitbook serve`。

**Comment by imcmy** [comment]
Thanks for reporting the issue. The URL is not correct in SUMMARY.md. Use "/" instead of "\".

Fixed in commit https://github.com/LinuxStory/Advanced-Bash-Scripting-Guide-in-Chinese/commit/ca71cf9a9c17e3709ca638925cf40ecec7416e26
